package documentFields

var ContractFields []Field = []Field{
	Field{"RegNum", "Номер реестровой записи", 0},
	Field{"Customer", "Наименование заказчика", 0},
	Field{"CustomerINN", "ИНН Заказчика", 0},
	Field{"CustomerKPP", "КПП Заказчика", 0},
	Field{"CustomerRegionGet", "Регион Заказчика", 0},
	Field{"FixBudgetSource", "Источник финансирования", 0},
	Field{"FixBudget", "Бюджет", 0},
	Field{"Placing", "Способ размещения закупки", 0},
	Field{"PurchaseNumberFix", "Номер закупки", 0},
	Field{"ObjectInfo", "Наименование закупки", 0},
	Field{"SignedXlsDate", "Дата заключения контракта", 0},
	Field{"Number", "Номер контракта", 0},
	Field{"NMCKFormat", "НМЦК", 0},
	Field{"NMCKUSDFormat", "НМЦК, долл. США", 0},
	Field{"TotalSumFormat", "Цена контракта, руб.", 0},
	Field{"TotalSumUSDFormat", "Цена контракта, долл. США", 0},
	Field{"Name", "Наименование товаров, работ и услуг", 0},
	Field{"OKPD", "Код по ОКПД", 0},
	Field{"OKPDInfo", "Расшифровка ОКПД", 0},
	Field{"Unit", "Единицы измерения", 0},
	Field{"PriceFormat", "Цена за единицу, руб.", 0},
	Field{"PriceUSDFormat", "Цена за единицу, долл. США", 0},
	Field{"Quantity", "Количество", 0},
	Field{"SumFormat", "Сумма, руб.", 0},
	Field{"SumUSDFormat", "Сумма, долл. США", 0},
	Field{"Supplier", "Поставщик", 0},
	Field{"SupplierAddress", "Место нахождения (место жительства) поставщика", 0},
	Field{"SupplierINN", "ИНН Поставщика", 0},
	Field{"SupplierPhone", "Телефон Поставщика", 0},
	Field{"ExecDate", "Дата окончания исполнения контракта", 0},
	Field{"PaidFormat", "Фактически оплачено", 0},
}
